print("Welcome to the tip calculator.")
bill = input("What was the total bill? $")
tip = input("What percentage tip would you like to give? 10, 12, or 15?")
number_of_people = input("How many people split the bill? ")
bill_as_float = float(bill)
tip_as_float = float(tip)
number_of_people_as_integer = int(number_of_people)
tip_amount = (bill_as_float / number_of_people_as_integer) * (tip_as_float /100)
full_amount = (bill_as_float / number_of_people_as_integer) + (tip_amount)
full_amount_rounded = "{:.2f}".format(full_amount)
print(f"Each person should pay: ${full_amount_rounded}")